//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC10_04
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OrdiniEntities : DbContext
    {
        public OrdiniEntities()
            : base("name=OrdiniEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OrdiniProdotti> OrdiniProdotti { get; set; }
        public virtual DbSet<OrdiniSet> OrdiniSet { get; set; }
        public virtual DbSet<ProdottiSet> ProdottiSet { get; set; }
    
        public virtual int ConfermaOrdine(Nullable<int> idOrdine, Nullable<int> idProdotto, Nullable<int> quantita)
        {
            var idOrdineParameter = idOrdine.HasValue ?
                new ObjectParameter("idOrdine", idOrdine) :
                new ObjectParameter("idOrdine", typeof(int));
    
            var idProdottoParameter = idProdotto.HasValue ?
                new ObjectParameter("idProdotto", idProdotto) :
                new ObjectParameter("idProdotto", typeof(int));
    
            var quantitaParameter = quantita.HasValue ?
                new ObjectParameter("Quantita", quantita) :
                new ObjectParameter("Quantita", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ConfermaOrdine", idOrdineParameter, idProdottoParameter, quantitaParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> DaiOrdine(Nullable<System.DateTime> data)
        {
            var dataParameter = data.HasValue ?
                new ObjectParameter("data", data) :
                new ObjectParameter("data", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("DaiOrdine", dataParameter);
        }
    }
}
